global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.your-provider.com:587'  # e.g., smtp.gmail.com:587
  smtp_auth_username: 'pranavbhat3105@gmail.com'
  smtp_auth_password: 'nbhq lmrd gfqf jxst'     # IMPORTANT: Use an application-specific password
  smtp_from: 'pranavbhat3105@gmail.com'
  smtp_require_tls: true
inhibit_rules:
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = critical
  target_matchers:
  - severity =~ warning|info
- equal:
  - namespace
  - alertname
  source_matchers:
  - severity = warning
  target_matchers:
  - severity = info
- equal:
  - namespace
  source_matchers:
  - alertname = InfoInhibitor
  target_matchers:
  - severity = info
- target_matchers:
  - alertname = InfoInhibitor
receivers:
- name: "null"
- name: "email-receiver"
  email_configs:
  - to: "pranavshruti51@gmail.com"
    send_resolved: true # Send a notification when the alert clears
    html: '{{ template "email.default.html" . }}'
route:
  group_by:
  - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: "email-receiver"  # <-- CHANGE THIS from "null" to "email-receiver"
  repeat_interval: 1h         # <-- Changed from 12h for better monitoring
  routes:
  - matchers:
    - alertname = "Watchdog"
    receiver: "null"
  # OPTIONAL: Explicitly route the HPA alert if you want to be sure
  - matchers:
    - alertname = "HighCPUTriggersHPA" # The name from your PrometheusRule
    receiver: "email-receiver"
templates:
- /etc/alertmanager/config/*.tmpl
