apiVersion: batch/v1
kind: Job
metadata:
  name: cpu-stress-test
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: stress-container
        image: polinux/stress 
        command: ["stress"]
        # Runs 2 workers that utilize CPU for 180 seconds
        args: ["--cpu", "2", "--timeout", "180s"]
      restartPolicy: Never
  backoffLimit: 4
